-- MySQL Script generated by MySQL Workbench
-- Wed May 11 05:45:41 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `rol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rol` ;

CREATE TABLE IF NOT EXISTS `rol` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user` ;

CREATE TABLE IF NOT EXISTS `user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL,
  `lastname` VARCHAR(250) NULL,
  `email` VARCHAR(100) NULL,
  `password` VARCHAR(100) NULL,
  `active` TINYINT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `rol_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_users_rol_idx` (`rol_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_rol`
    FOREIGN KEY (`rol_id`)
    REFERENCES `rol` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `category` ;

CREATE TABLE IF NOT EXISTS `category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(250) NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `book`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `book` ;

CREATE TABLE IF NOT EXISTS `book` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cover_image` VARCHAR(200) NULL,
  `title` VARCHAR(250) NULL,
  `year_publication` INT NULL,
  `author` VARCHAR(250) NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `category_id` INT NOT NULL,
  `image_code` TEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_book_category1_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `fk_book_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `book_has_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `book_has_user` ;

CREATE TABLE IF NOT EXISTS `book_has_user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `book_id` INT NULL,
  `user_id` INT NULL,
  `borrow` TINYINT NULL,
  `date_borrow` DATETIME NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX `fk_book_has_user_user1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_book_has_user_book1_idx` (`book_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_book_has_user_book1`
    FOREIGN KEY (`book_id`)
    REFERENCES `book` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_book_has_user_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `rol`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `rol` (`id`, `name`, `created_at`, `updated_at`) VALUES (DEFAULT, 'admin', DEFAULT, DEFAULT);
INSERT INTO `rol` (`id`, `name`, `created_at`, `updated_at`) VALUES (DEFAULT, 'user', DEFAULT, DEFAULT);

COMMIT;


-- -----------------------------------------------------
-- Data for table `user`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `user` (`id`, `name`, `lastname`, `email`, `password`, `active`, `created_at`, `updated_at`, `rol_id`) VALUES (DEFAULT, 'Marco', 'Lopez', 'admin@admin.com', '12345+', 1, DEFAULT, DEFAULT, 1);
INSERT INTO `user` (`id`, `name`, `lastname`, `email`, `password`, `active`, `created_at`, `updated_at`, `rol_id`) VALUES (DEFAULT, 'Jose', 'Lopez', 'jose@mail.com', 'jose2022+', 1, DEFAULT, DEFAULT, 2);

COMMIT;


-- -----------------------------------------------------
-- Data for table `category`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `category` (`id`, `name`, `created_at`, `updated_at`) VALUES (DEFAULT, 'Ciencia ficción', DEFAULT, DEFAULT);
INSERT INTO `category` (`id`, `name`, `created_at`, `updated_at`) VALUES (DEFAULT, 'Literatura', DEFAULT, DEFAULT);
INSERT INTO `category` (`id`, `name`, `created_at`, `updated_at`) VALUES (DEFAULT, 'Biografias', DEFAULT, DEFAULT);
INSERT INTO `category` (`id`, `name`, `created_at`, `updated_at`) VALUES (DEFAULT, 'Monografias', DEFAULT, DEFAULT);

COMMIT;

